using System;
using NXOpen;
using NXOpen.Features;
using NXOpen.UF;
using OptellixParametricBlock.Geometry;
using OptellixParametricBlock.Models;
using OptellixParametricBlock.UI;
using OptellixParametricBlock.Validation;

namespace OptellixParametricBlock
{
    /// <summary>
    /// Entry Point for Siemens NX Open Application.
    /// Handles command execution rules, environment validation, undo mark wrapping, and exception recovery.
    /// </summary>
    public class EntryPoint
    {
        // The supplied DLX was authored outside NX Block UI Styler and can cause NX
        // to block while loading it. Keep the production geometry test independent
        // of that dialog until NX regenerates a valid DLX file.
        private static readonly bool UseBlockStylerDialog = true;

        public static void Main(string[] args)
        {
            ExecuteApplication();
        }

        public static int ufusr(string param)
        {
            ExecuteApplication();
            return 0;
        }

        public static int GetUnloadOption(string dummy)
        {
            return (int)Session.LibraryUnloadOption.Explicitly;
        }

        /// <summary>
        /// Main application controller flow.
        /// </summary>
        public static void ExecuteApplication()
        {
            Session session = Session.GetSession();
            NXOpen.UI ui = NXOpen.UI.GetUI();

            // 1. Validate Execution Context
            if (!ValidateWorkPartContext(session, ui))
            {
                return;
            }

            Part workPart = session.Parts.Work;
            Session.UndoMarkId undoMark = (Session.UndoMarkId)0;

            try
            {
                // 2. Set Undo Mark for single-operation rollback
                undoMark = session.SetUndoMark(Session.MarkVisibility.Visible, "OPTELLIX_PARAMETRIC_BLOCK");

                // 3. Obtain Session Parameters (persistent across NX session invocations)
                BlockParameters parameters = BlockParameters.GetSessionInstance();

                // 4. Execute the NX 2412 geometry pipeline. A Block UI Styler dialog
                // can be re-enabled after its DLX is generated by NX Block UI Styler.
                if (UseBlockStylerDialog)
                {
                    using (ParametricBlockDialog dialog = new ParametricBlockDialog())
                    {
                        dialog.Show();
                    }
                }
                else
                {
                    ExecuteGeometryDirect(session, workPart, parameters, ui);
                }
            }
            catch (NXException nxEx)
            {
                // Perform Undo Rollback on Failure
                if (undoMark != (Session.UndoMarkId)0)
                {
                    session.UndoToMark(undoMark, "OPTELLIX_PARAMETRIC_BLOCK");
                }
                session.LogFile.WriteLine(nxEx.ToString());
                ui.NXMessageBox.Show("NX API Exception", NXMessageBox.DialogType.Error, nxEx.Message);
            }
            catch (Exception ex)
            {
                if (undoMark != (Session.UndoMarkId)0)
                {
                    session.UndoToMark(undoMark, "OPTELLIX_PARAMETRIC_BLOCK");
                }
                session.LogFile.WriteLine(ex.ToString());
                ui.NXMessageBox.Show("Unexpected Error", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        /// <summary>
        /// Validates that an active work part exists, is a standard Part (not Assembly or Drawing),
        /// and is modifiable (not read-only or part family member).
        /// </summary>
        public static bool ValidateWorkPartContext(Session session, NXOpen.UI ui)
        {
            Part workPart = session.Parts.Work;

            // Rule 1: Validate active work part exists
            if (workPart == null)
            {
                ui.NXMessageBox.Show(
                    "Command Execution Blocked",
                    NXMessageBox.DialogType.Error,
                    "No active work part found in the current NX session. Please open or create a Part file.");
                return false;
            }

            // Rule 2: Reject Assemblies
            if (workPart.ComponentAssembly != null && workPart.ComponentAssembly.RootComponent != null)
            {
                // Check if part contains sub-components (is assembly)
                if (workPart.ComponentAssembly.RootComponent.GetChildren().Length > 0)
                {
                    ui.NXMessageBox.Show(
                        "Command Execution Blocked",
                        NXMessageBox.DialogType.Error,
                        "Parametric Block Plus can only be executed in a standalone Part file, not an Assembly context.");
                    return false;
                }
            }

            // Rule 3: Reject Drawing Sheets
            if (workPart.DrawingSheets.ToArray().Length > 0)
            {
                ui.NXMessageBox.Show(
                    "Command Execution Blocked",
                    NXMessageBox.DialogType.Error,
                    "Parametric Block Plus cannot be executed within a Drawing Sheet context.");
                return false;
            }

            // Rule 4: Reject Read-only parts or Part Family Members
            if (workPart.IsReadOnly)
            {
                ui.NXMessageBox.Show(
                    "Command Execution Blocked",
                    NXMessageBox.DialogType.Error,
                    "The active work part is Read-Only or a Part Family member and cannot be modified.");
                return false;
            }

            return true;
        }

        /// <summary>
        /// Direct execution pipeline for testing or non-dialog invocation.
        /// </summary>
        private static void ExecuteGeometryDirect(Session session, Part workPart, BlockParameters parameters, NXOpen.UI ui)
        {
            // Validate inputs
            var valResult = ParametricValidator.Validate(parameters);
            if (!valResult.IsValid)
            {
                ui.NXMessageBox.Show("Validation Error", NXMessageBox.DialogType.Error, valResult.ErrorMessage);
                return;
            }

            Session.UndoMarkId mark = session.SetUndoMark(
                Session.MarkVisibility.Invisible,
                "OPTELLIX_PARAMETRIC_BLOCK_APPLY");
            try
            {
                var baseService = new BaseBlockService(session);
                var seedService = new SeedHoleService(session);
                var patternService = new HolePatternService(session);
                var chamferService = new TopChamferService(session);

                Feature baseFeat = baseService.CreateOrUpdateBlock(workPart, parameters);
                Feature seedFeat = seedService.CreateOrUpdateSeedHole(workPart, baseFeat, parameters);
                Feature patternFeat = patternService.CreateOrUpdatePattern(workPart, seedFeat, parameters);
                // Pattern features do not own/expose the result body.  The base
                // extrude's outer top edges are stable references for the chamfer.
                chamferService.CreateOrUpdateTopChamfer(workPart, baseFeat, parameters);

                int updateErrors = session.UpdateManager.DoUpdate(mark);
                if (updateErrors != 0)
                {
                    throw new InvalidOperationException($"NX model update failed with {updateErrors} error(s).");
                }

                ui.NXMessageBox.Show(
                    "Parametric Block Plus",
                    NXMessageBox.DialogType.Information,
                    "Parametric Block and Patterned Secondary Features successfully created / updated.");
            }
            catch (Exception ex)
            {
                if (mark != (Session.UndoMarkId)0)
                {
                    session.UndoToMark(mark, "OPTELLIX_PARAMETRIC_BLOCK_APPLY");
                }
                session.LogFile.WriteLine($"Optellix Direct Geometry Execution Error: {ex}");
                ui.NXMessageBox.Show("Execution Error", NXMessageBox.DialogType.Error, ex.Message);
            }
        }
    }
}
